In [69]:
from IPython.display import display, Math, Latex

from sympy.interactive import printing
printing.init_printing(use_latex=True)

from __future__ import division

import matplotlib
matplotlib.rc('font',**{'family':'serif'})

#  Pure spin-orbit state mixing

Mix the states with the same $L$ (and $m_L$) and the same elctron configuration $\mid 5s5p \rangle$

LHS: mixed spin-orbit states, RHS: pure spin-orbit states

$\mid ^3 P_0 \rangle = \mid ^3 P^0_0 \rangle$

$\mid ^3 P_1 \rangle = \alpha \mid ^3 P_1^0 \rangle + \beta \mid ^1 P_1^0 \rangle$

$\mid ^3 P_2 \rangle = \mid ^3 P_2^0 \rangle$

$\mid ^1 P_1 \rangle = -\beta \mid ^3 P_1^0 \rangle + \alpha \mid ^1P_1^0 \rangle$

The intermediate coupling coefficients are determined by

$\frac{\alpha^2}{\beta^2} = \frac{\tau^{^3P_1}}{\tau^{^1P_1}} (\frac{\nu^{^3P1}}{\nu^{^1P1}})^3$, $\alpha^2 + \beta^2 = 1$

In [70]:
# Ratio of (alpha/beta)^2, according to Stellmer
from math import sqrt

c = (434829 / 650504)**3 * (30.5 / 0.0074)

# The beta coefficient is negative, according to Boyd 2007
beta = - sqrt(1 / (1 + c))
alpha = sqrt(c / (1 + c))
print (alpha, beta)

(0.9995940880788805, -0.028489631056776547)


# Hyperfine state mixing

In [2]:
alpha_0 = 2E-4
beta_0 = -4E-6
gamma_0 = -1E-6
alpha_1 = alpha_0 * alpha - beta_0 * beta
beta_1 = alpha_0 * beta + beta_0 * alpha
gamma_1 = gamma_0
print (alpha_1, beta_1, gamma_1)

(0.000199804859091549, -9.69630256367083e-06, -1e-06)


The lifetime of $^3P_0$ is given by

$\tau^{^3P_0} = (\frac{\lambda^{^3P_0 - ^1S_0}}{\lambda^{^3P_1 - ^1S_0}})^3 \frac{\beta^2}{(\alpha_0 \beta + \beta_0 \alpha)^2} \tau^{^3P_1}$

which is 193 seconds

In [3]:
from math import pi
(698 / 689)**3 * (beta / (alpha_0 * beta + beta_0 * alpha))**2 * 1 / (2 * pi * 7400)

193.04490629469151

We already have

$\mid ^3 P_0 \rangle = \mid ^3 P_0^0 \rangle + (\alpha_0 \alpha - \beta_0 \beta) \mid ^3 P_1^0 \rangle + (\alpha_0 \beta + \beta_0 \alpha) \mid ^1 P_1^0 \rangle + \gamma_0 \mid ^3 P_2^0 \rangle = \mid ^3 P_0^0 \rangle + \alpha_1 \mid ^3 P_1^0 \rangle + \beta_1 \mid ^1 P_1^0 \rangle + \gamma_1 \mid ^3 P_2^0 \rangle$

And ignore higher order of hyperfine mixing

$\mid ^3 P_1 \rangle = \alpha \mid ^3 P_1^0 \rangle + \beta \mid ^1 P_1^0 \rangle$

$\mid ^3 P_2 \rangle = \mid ^3 P_2^0 \rangle$

$\mid ^1 P_1 \rangle = -\beta \mid ^3 P_1^0 \rangle + \alpha \mid ^1P_1^0 \rangle$

# Hyperfine coupling

The magnetic dipole ($A$) and electric quadrupole ($Q$) contributions to the hyperfine interaction are

$H_A = A \vec{I} \cdot \vec{J}$

$H_Q = Q \frac{\frac{3}{2} \vec{I} \cdot \vec{J} (2 \vec{I} \cdot \vec{J} + 1) - IJ(I+1) (J+1)}{2IJ(2I-1)(2J-1)}$

Basically they couple states with the same $F$ ($\vec{F} = \vec{I} + \vec{J}$) and $m_F$. For these excited states,


$\mid ^3 P_1 \rangle: A = -260$ MHz, $Q = -35 $MHz

$\mid ^3 P_2 \rangle: A = -212 $ MHz, $Q = 67 $MHz 

$\mid ^1 P_1 \rangle: A = -3.4 $ MHz, $Q = 39$ MHz 

In [4]:
# In units of MHz
A_3P1 = -260
Q_3P1 = -35
A_3P2 = -212
Q_3P2 = 67
A_1P1 = -3.4
Q_1P1 = 39

# Zeeman interaction with external magnetic field

$H_z = (g_S S_z + g_L L_z - g_I I_z) \mu_0 B$

where $g_S = 2, g_L = 1, g_I = \frac{\mu_I (1-\sigma_d)}{\mu_0 I}$

For $^{87} Sr$, $\mu_I = -1.09247 \mu_N, \sigma_d = 0.00345$ ($\sigma_d$ diamagnetic correction)

Then the full treatment including Zeeman interactions and HFI is

$H = H_Z + H_A + H_Q$

we assume these interactions are smaller than the fine structure such that we can use the spin-orbit mixed states as a basis.

# Clebsch-Gordan coefficients

## 1. Fine structure

We first express the pure spin-orbit states $\mid ^{2S + 1} P _ J ^0, m_J \rangle$ as a superposition of $\mid ^{2S + 1} P _ J ^0, m_S, m_L \rangle$ states using CG coefficients

$\mid ^{2S + 1} P _ J ^0, m_J \rangle = \sum_{m_S, m_L} C^{J, m_J}_{S, m_S, L, m_L} \mid ^{2S + 1} P _ J ^0, m_S, m_L \rangle$

Explicitly, we have

$\mid ^{3} P _ 0 ^0,  0\rangle = \mid ^{3} P _ 0 ^0, 0, 0 \rangle$


--------------------

$\mid ^{3} P _ 1 ^0, 1 \rangle = \frac{1}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, 1, 0 \rangle - \mid ^{3} P _ 1 ^0, 0, 1 \rangle)$

$\mid ^{3} P _ 1 ^0, 0 \rangle = \frac{1}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, 1, -1 \rangle - \mid ^{3} P _ 1 ^0, -1, 1 \rangle)$

$\mid ^{3} P _ 1 ^0, -1 \rangle = \frac{1}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, -1, 0 \rangle - \mid ^{3} P _ 1 ^0, 0, -1 \rangle)$

------------------

$\mid ^{3} P _ 2 ^0, 2 \rangle = \mid ^{3} P _ 2 ^0, 1, 1 \rangle $

$\mid ^{3} P _ 2 ^0, 1 \rangle = \frac{1}{\sqrt{2}}(\mid ^{3} P _ 2 ^0, 1, 0 \rangle + \mid ^{3} P _ 2 ^0, 0, 1 \rangle)$

$\mid ^{3} P _ 2 ^0, 0 \rangle = \frac{\sqrt{2}}{\sqrt{3}}\mid ^{3} P _ 2 ^0, 0, 0 \rangle + \frac{1}{\sqrt{6}}\mid ^{3} P _ 2 ^0, 1, -1 \rangle + \frac{1}{\sqrt{6}}\mid ^{3} P _ 2 ^0, -1, 1 \rangle$

$\mid ^{3} P _ 2 ^0, -1 \rangle = \frac{1}{\sqrt{2}}(\mid ^{3} P _ 2 ^0, -1, 0 \rangle + \mid ^{3} P _ 2 ^0, 0, -1 \rangle)$

$\mid ^{3} P _ 2 ^0, -2 \rangle = \mid ^{3} P _ 2 ^0, -1, -1 \rangle $

--------------------

$\mid ^{1} P _ 1 ^0, 1 \rangle = \mid ^{1} P _ 1 ^0, 0, 1 \rangle $

$\mid ^{1} P _ 1 ^0, 0 \rangle = \mid ^{1} P _ 1 ^0, 0, 1 \rangle $

$\mid ^{1} P _ 1 ^0, -1 \rangle = \mid ^{1} P _ 1 ^0, 0, -1 \rangle$

For the mixed spin-orbit states, we have

$\mid ^{3} P _ 0,  0\rangle = \mid ^{3} P _ 0 ^0, 0, 0 \rangle$


--------------------

$\mid ^{3} P _ 1, 1 \rangle = \frac{\alpha}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, 1, 0 \rangle - \mid ^{3} P _ 1 ^0, 0, 1 \rangle) + \beta \mid ^{1} P _ 1 ^0, 0, 1 \rangle$

$\mid ^{3} P _ 1, 0 \rangle = \frac{\alpha}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, 1, -1 \rangle - \mid ^{3} P _ 1 ^0, -1, 1 \rangle) + \beta \mid ^{1} P _ 1 ^0, 0, 0 \rangle$

$\mid ^{3} P _ 1, -1 \rangle = \frac{\alpha}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, -1, 0 \rangle - \mid ^{3} P _ 1 ^0, 0, -1 \rangle) + \beta \mid ^{1} P _ 1 ^0, 0, -1 \rangle$

------------------

$\mid ^{3} P _ 2 , 2 \rangle = \mid ^{3} P _ 2 ^0, 1, 1 \rangle $

$\mid ^{3} P _ 2 , 1 \rangle = \frac{1}{\sqrt{2}}(\mid ^{3} P _ 2 ^0, 1, 0 \rangle + \mid ^{3} P _ 2 ^0, 0, 1 \rangle)$

$\mid ^{3} P _ 2 , 0 \rangle = \frac{\sqrt{2}}{\sqrt{3}}\mid ^{3} P _ 2 ^0, 0, 0 \rangle + \frac{1}{\sqrt{6}}\mid ^{3} P _ 2 ^0, 1, -1 \rangle + \frac{1}{\sqrt{6}}\mid ^{3} P _ 2 ^0, -1, 1 \rangle$

$\mid ^{3} P _ 2 , -1 \rangle = \frac{1}{\sqrt{2}}(\mid ^{3} P _ 2 ^0, -1, 0 \rangle + \mid ^{3} P _ 2 ^0, 0, -1 \rangle)$

$\mid ^{3} P _ 2 , -2 \rangle = \mid ^{3} P _ 2 ^0, -1, -1 \rangle $

--------------------

$\mid ^{1} P _ 1, 1 \rangle = -\frac{\beta}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, 1, 0 \rangle - \mid ^{3} P _ 1 ^0, 0, 1 \rangle) + \alpha \mid ^{1} P _ 1 ^0, 0, 1 \rangle$

$\mid ^{1} P _ 1, 0 \rangle = -\frac{\beta}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, 1, -1 \rangle - \mid ^{3} P _ 1 ^0, -1, 1 \rangle) + \alpha \mid ^{1} P _ 1 ^0, 0, 0 \rangle$

$\mid ^{1} P _ 1, -1 \rangle = -\frac{\beta}{\sqrt{2}}(\mid ^{3} P _ 1 ^0, -1, 0 \rangle - \mid ^{3} P _ 1 ^0, 0, -1 \rangle) + \alpha \mid ^{1} P _ 1 ^0, 0, -1 \rangle$

In [5]:
from sympy.physics.quantum.cg import CG
from sympy import S
for s in [-1, 0, 1]:
    cg = CG(1, s, S(9)/2, S(3)/2 - s, S(11)/2, S(3)/2)
    print cg.doit()

sqrt(330)/55
2*sqrt(385)/55
sqrt(1155)/55


In [64]:
# CG coefficients

from sympy.physics.quantum.cg import CG
from sympy import S
from numpy import zeros, ones, array

# 3P1 states.
CG_3P1 = zeros((3,3))
CG_3P2 = zeros((5,3))
CG_1P1 = zeros((3,1))
CG_3P0 = zeros((1,3))

# 3P1, S, L, m_S, m_L, J, m_J
Eigen_3P1 = zeros((3,3),dtype='S3, d, d, d, d, d, d')
Eigen_3P2 = zeros((5,3),dtype='S3, d, d, d, d, d, d')
Eigen_1P1 = zeros((3,1),dtype='S3, d, d, d, d, d, d')
Eigen_3P0 = zeros((1,3),dtype='S3, d, d, d, d, d, d')

CGcoefficients1 = [CG_3P1, CG_3P2, CG_1P1, CG_3P0]
Eigenvalues1 = [Eigen_3P1, Eigen_3P2, Eigen_1P1, Eigen_3P0]


# 3P1 states
# (m, n) indexes, (j, s) = (m_J, m_S)
for m, j in enumerate(range(-1, 2, 1)):
    for n, s in enumerate(range(-1, 2, 1)):
        cg = CG(1, s, 1, j - s, 1, j)
        CGcoefficients1[0][m][n] = cg.doit()
        Eigenvalues1[0][m][n][0] = '3P1'
        Eigenvalues1[0][m][n][1] = 1
        Eigenvalues1[0][m][n][2] = 1
        Eigenvalues1[0][m][n][3] = s
        Eigenvalues1[0][m][n][4] = j - s
        Eigenvalues1[0][m][n][5] = 1
        Eigenvalues1[0][m][n][6] = j
            
# 3P2 states
for m, j in enumerate(range(-2, 3, 1)):
    for n, s in enumerate(range(-1, 2, 1)):
        cg = CG(1, s, 1, j - s, 2, j)
        CGcoefficients1[1][m][n] = cg.doit()
        Eigenvalues1[1][m][n][0] = '3P2'
        Eigenvalues1[1][m][n][1] = 1
        Eigenvalues1[1][m][n][2] = 1
        Eigenvalues1[1][m][n][3] = s
        Eigenvalues1[1][m][n][4] = j - s
        Eigenvalues1[1][m][n][5] = 2
        Eigenvalues1[1][m][n][6] = j
            

# 1P1 states
for m, j in enumerate(range(-1, 2, 1)):
    cg = CG(0, 0, 1, j, 1, j)
    CGcoefficients1[2][m][0] = cg.doit()
    Eigenvalues1[2][m][0][0] = '1P1'
    Eigenvalues1[2][m][0][1] = 0
    Eigenvalues1[2][m][0][2] = 1
    Eigenvalues1[2][m][0][3] = 0
    Eigenvalues1[2][m][0][4] = j
    Eigenvalues1[2][m][0][5] = 1
    Eigenvalues1[2][m][0][6] = j
            
# 3P0 states
for n, s in enumerate(range(-1, 2, 1)):
    cg = CG(1, s, 1, -1 * s, 0, 0)
    CGcoefficients1[3][0][n] = cg.doit()
    Eigenvalues1[3][0][n][0] = '3P0'
    Eigenvalues1[3][0][n][1] = 1
    Eigenvalues1[3][0][n][2] = 1
    Eigenvalues1[3][0][n][3] = s
    Eigenvalues1[3][0][n][4] = -1 * s
    Eigenvalues1[3][0][n][5] = 0
    Eigenvalues1[3][0][n][6] = 0
         
print CG_3P2
print Eigen_3P2

[[ 1.          0.          0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.40824829  0.81649658  0.40824829]
 [ 0.          0.70710678  0.70710678]
 [ 0.          0.          1.        ]]
[[('3P2', 1.0, 1.0, -1.0, -1.0, 2.0, -2.0)
  ('3P2', 1.0, 1.0, 0.0, -2.0, 2.0, -2.0)
  ('3P2', 1.0, 1.0, 1.0, -3.0, 2.0, -2.0)]
 [('3P2', 1.0, 1.0, -1.0, 0.0, 2.0, -1.0)
  ('3P2', 1.0, 1.0, 0.0, -1.0, 2.0, -1.0)
  ('3P2', 1.0, 1.0, 1.0, -2.0, 2.0, -1.0)]
 [('3P2', 1.0, 1.0, -1.0, 1.0, 2.0, 0.0)
  ('3P2', 1.0, 1.0, 0.0, 0.0, 2.0, 0.0)
  ('3P2', 1.0, 1.0, 1.0, -1.0, 2.0, 0.0)]
 [('3P2', 1.0, 1.0, -1.0, 2.0, 2.0, 1.0)
  ('3P2', 1.0, 1.0, 0.0, 1.0, 2.0, 1.0)
  ('3P2', 1.0, 1.0, 1.0, 0.0, 2.0, 1.0)]
 [('3P2', 1.0, 1.0, -1.0, 3.0, 2.0, 2.0)
  ('3P2', 1.0, 1.0, 0.0, 2.0, 2.0, 2.0)
  ('3P2', 1.0, 1.0, 1.0, 1.0, 2.0, 2.0)]]


In [67]:
# Include spin-orbit and HF state mixing
# Enough to calculate the 3P2 3P1 1P1 states Zeeman shift
from numpy import concatenate

CG_3P1_c = concatenate((alpha * CG_3P1, beta * CG_1P1), axis=1)
CG_3P2_c = CG_3P2
CG_1P1_c = concatenate((alpha * CG_1P1, -1 * beta * CG_3P1), axis=1)
CG_3P0_c = CG_3P0

Eigen_3P1_c = concatenate((Eigen_3P1, Eigen_1P1), axis=1)
Eigen_3P2_c = Eigen_3P2
Eigen_1P1_c = concatenate((Eigen_1P1, Eigen_3P1), axis=1)
Eigen_3P0_c = Eigen_3P0

CGcoefficients2 = [CG_3P1_c, CG_3P2_c, CG_1P1_c, CG_3P0_c]
Eigenvalues2 = [Eigen_3P1_c, Eigen_3P2_c, Eigen_1P1_c, Eigen_3P0_c]

print CG_1P1_c
print Eigen_3P1_c

[[ 0.99959409 -0.02014521  0.02014521  0.        ]
 [ 0.99959409 -0.02014521  0.          0.02014521]
 [ 0.99959409  0.         -0.02014521  0.02014521]]
[[('3P1', 1.0, 1.0, -1.0, 0.0, 1.0, -1.0)
  ('3P1', 1.0, 1.0, 0.0, -1.0, 1.0, -1.0)
  ('3P1', 1.0, 1.0, 1.0, -2.0, 1.0, -1.0)
  ('1P1', 0.0, 1.0, 0.0, -1.0, 1.0, -1.0)]
 [('3P1', 1.0, 1.0, -1.0, 1.0, 1.0, 0.0)
  ('3P1', 1.0, 1.0, 0.0, 0.0, 1.0, 0.0)
  ('3P1', 1.0, 1.0, 1.0, -1.0, 1.0, 0.0)
  ('1P1', 0.0, 1.0, 0.0, 0.0, 1.0, 0.0)]
 [('3P1', 1.0, 1.0, -1.0, 2.0, 1.0, 1.0)
  ('3P1', 1.0, 1.0, 0.0, 1.0, 1.0, 1.0)
  ('3P1', 1.0, 1.0, 1.0, 0.0, 1.0, 1.0)
  ('1P1', 0.0, 1.0, 0.0, 1.0, 1.0, 1.0)]]


## 2. Hyperfine structure

Then we have

$\mid ^{2S + 1} P _ J , F, m_F \rangle = \sum_{m_J, m_I} C^{F, m_F}_{J, m_J, I, m_I} \mid ^{2S + 1} P _ J, m_J, m_I \rangle$

Explicitly, we have


$\mid ^{3} P _ 0, \frac{9}{2}, m_F\rangle = \mid ^{3} P _ 0, 0, m_F \rangle$


--------------------

$\mid ^{3} P _ 1, \frac{11}{2}, \frac{11}{2}\rangle = \mid ^{3} P _ 1, 1, \frac{9}{2} \rangle$

$\mid ^{3} P _ 1, \frac{11}{2}, \frac{9}{2}\rangle = \frac{\sqrt{2}}{\sqrt{11}}\mid ^{3} P _ 1, 0, \frac{9}{2} \rangle + \frac{3}{\sqrt{11}} \mid ^{3} P _ 1, 1, \frac{7}{2} \rangle $

$\mid ^{3} P _ 1, \frac{11}{2}, \frac{7}{2}\rangle = \frac{1}{\sqrt{55}}\mid ^{3} P _ 1, -1, \frac{9}{2} \rangle + \frac{3\sqrt{2}}{\sqrt{55}} \mid ^{3} P _ 1, 0, \frac{7}{2} \rangle+ \frac{6}{\sqrt{55}} \mid ^{3} P _ 1, 1, \frac{5}{2} \rangle  $

$\mid ^{3} P _ 1, \frac{11}{2}, \frac{5}{2}\rangle = \frac{\sqrt{3}}{\sqrt{55}}\mid ^{3} P _ 1, -1, \frac{7}{2} \rangle + \frac{2\sqrt{6}}{\sqrt{55}} \mid ^{3} P _ 1, 0, \frac{5}{2} \rangle+ \frac{2 \sqrt{7}}{\sqrt{55}} \mid ^{3} P _ 1, 1, \frac{3}{2} \rangle  $

$\mid ^{3} P _ 1, \frac{11}{2}, \frac{3}{2}\rangle = \frac{\sqrt{6}}{\sqrt{55}}\mid ^{3} P _ 1, -1, \frac{5}{2} \rangle + \frac{2\sqrt{7}}{\sqrt{55}} \mid ^{3} P _ 1, 0, \frac{3}{2} \rangle+ \frac{\sqrt{21}}{\sqrt{55}} \mid ^{3} P _ 1, 1, \frac{1}{2} \rangle  $

....

Too complicated

### $^3P_1$  $^3P_2$ $^1P_1$states

In [8]:
# CG coefficients

from sympy.physics.quantum.cg import CG
from sympy import S
from numpy import zeros, ones, array

# 3P1 states, F = 11/2, 9/2...
CG_3P1_11 = zeros((12,3))
CG_3P1_9 = zeros((10,3))
CG_3P1_7 = zeros((8,3))
CG_3P2_13 = zeros((14,5))
CG_3P2_11 = zeros((12,5))
CG_3P2_9 = zeros((10,5))
CG_3P2_7 = zeros((8,5))
CG_3P2_5 = zeros((6,5))
CG_1P1_11 = zeros((12,3))
CG_1P1_9 = zeros((10,3))
CG_1P1_7 = zeros((8,3))
CG_3P0_9 = ones((10,1))

print 'CG_3P' + str(2) + '_' + str(5)

# 3P1, J, I, m_J, m_I, F, m_F
Eigen_3P1_11 = zeros((12,3),dtype='S3, d, d, d, d, d, d')
Eigen_3P1_9 = zeros((10,3),dtype='S3, d, d, d, d, d, d')
Eigen_3P1_7 = zeros((8,3),dtype='S3, d, d, d, d, d, d')
Eigen_3P2_13 = zeros((14,5),dtype='S3, d, d, d, d, d, d')
Eigen_3P2_11 = zeros((12,5),dtype='S3, d, d, d, d, d, d')
Eigen_3P2_9 = zeros((10,5),dtype='S3, d, d, d, d, d, d')
Eigen_3P2_7 = zeros((8,5),dtype='S3, d, d, d, d, d, d')
Eigen_3P2_5 = zeros((6,5),dtype='S3, d, d, d, d, d, d')
Eigen_1P1_11 = zeros((12,3),dtype='S3, d, d, d, d, d, d')
Eigen_1P1_9 = zeros((10,3),dtype='S3, d, d, d, d, d, d')
Eigen_1P1_7 = zeros((8,3),dtype='S3, d, d, d, d, d, d')
Eigen_3P0_9 = zeros((10,1),dtype='S3, d, d, d, d, d, d')

CGcoefficients = [CG_3P1_11, CG_3P1_9, CG_3P1_7, CG_3P2_13, CG_3P2_11, CG_3P2_9, CG_3P2_7, CG_3P2_5, CG_1P1_11, CG_1P1_9, CG_1P1_7, CG_3P0_9]
Eigenvalues = [Eigen_3P1_11, Eigen_3P1_9, Eigen_3P1_7, Eigen_3P2_13, Eigen_3P2_11, Eigen_3P2_9, Eigen_3P2_7, Eigen_3P2_5, Eigen_1P1_11, Eigen_1P1_9, Eigen_1P1_7, Eigen_3P0_9]


# 3P1 & 1P1 states
# (p, m, n) indexes, (k, i, j) = (F, m_F, m_J)
for p, k in enumerate(range(11, 5, -2)):
    for m, i in enumerate(range(-k, k + 2, 2)):
        for n, j in enumerate(range(-1, 2, 1)):
            cg = CG(1, j, S(9)/2, S(i)/2 - j, S(k)/2, S(i)/2)
            CGcoefficients[p][m][n] = cg.doit()
            Eigenvalues[p][m][n][0] = '3P1'
            Eigenvalues[p][m][n][1] = 1
            Eigenvalues[p][m][n][2] = 9/2
            Eigenvalues[p][m][n][3] = j 
            Eigenvalues[p][m][n][4] = i/2 - j
            Eigenvalues[p][m][n][5] = k/2
            Eigenvalues[p][m][n][6] = i/2
            CGcoefficients[p + 8][m][n] = cg.doit()
            Eigenvalues[p + 8][m][n][0] = '1P1'
            Eigenvalues[p + 8][m][n][1] = 1
            Eigenvalues[p + 8][m][n][2] = 9/2
            Eigenvalues[p + 8][m][n][3] = j 
            Eigenvalues[p + 8][m][n][4] = i/2 - j
            Eigenvalues[p + 8][m][n][5] = k/2
            Eigenvalues[p + 8][m][n][6] = i/2
            
# 3P2 states
for p, k in enumerate(range(13, 3, -2)):
    for m, i in enumerate(range(-k, k + 2, 2)):
        for n, j in enumerate(range(-2, 3, 1)):
            cg = CG(2, j, S(9)/2, S(i)/2 - j, S(k)/2, S(i)/2)
            CGcoefficients[p + 3][m][n] = cg.doit()
            Eigenvalues[p + 3][m][n][0] = '3P2'
            Eigenvalues[p + 3][m][n][1] = 2
            Eigenvalues[p + 3][m][n][2] = 9/2
            Eigenvalues[p + 3][m][n][3] = j
            Eigenvalues[p + 3][m][n][4] = i/2 - j
            Eigenvalues[p + 3][m][n][5] = k/2
            Eigenvalues[p + 3][m][n][6] = i/2
            

# 3P0 state

for m, i in enumerate(range(-9, 11, 2)):
    Eigenvalues[11][m][0][0] = '3P0'
    Eigenvalues[11][m][0][1] = 1
    Eigenvalues[11][m][0][2] = 9/2
    Eigenvalues[11][m][0][3] = 0
    Eigenvalues[11][m][0][4] = i/2
    Eigenvalues[11][m][0][5] = 9/2
    Eigenvalues[11][m][0][6] = i/2
         
print CG_3P1_11[0]
print Eigen_3P1_11[0]

CG_3P2_5
[ 1.  0.  0.]
[('3P1', 1.0, 4.5, -1.0, -4.5, 5.5, -5.5)
 ('3P1', 1.0, 4.5, 0.0, -5.5, 5.5, -5.5)
 ('3P1', 1.0, 4.5, 1.0, -6.5, 5.5, -5.5)]


# Matrix elements of HFI

$ H_{HF} = A \vec{I} \cdot \vec{J} + Q \frac{\frac{3}{2} \vec{I} \cdot \vec{J} (2 \vec{I} \cdot \vec{J} + 1) - IJ(I+1) (J+1)}{2IJ(2I-1)(2J-1)}$

Using $\vec{I} \cdot \vec{J} = I_z J_z + \frac{1}{2} (I_+ J_- + I_- J_+)$

$J_+ \mid {J, m_J} \rangle = \hbar \sqrt{(J - m_J)(J + m_J + 1)} \mid {J, m_J + 1} \rangle$

$J_- \mid {J, m_J} \rangle = \hbar \sqrt{(J + m_J)(J - m_J + 1)} \mid {J, m_J - 1} \rangle$

and similar for $I_+, I_-$

$I_- J_+ \mid {J, I, m_J, m_I} \rangle = \sqrt{(I + m_I)(I - m_I + 1)}\sqrt{(J - m_J)(J + m_J + 1)} \mid {J, I, m_J + 1, m_I - 1} \rangle$

$I_+ J_- \mid {J, I, m_J, m_I} \rangle =  \sqrt{(I - m_I)(I + m_I + 1)}\sqrt{(J + m_J)(J - m_J + 1)} \mid {J, I, m_J - 1, m_I + 1} \rangle$

Then 

$\vec{I} \cdot \vec{J} \mid J, \frac{9}{2}, m_J, m_I \rangle = m_I m_J \mid {J, \frac{9}{2}, m_J, m_I} \rangle + \frac{1}{2}  \sqrt{(\frac{9}{2} - m_I)(\frac{9}{2} + m_I + 1)}\sqrt{(J + m_J)(J - m_J + 1)} \mid {J, \frac{9}{2}, m_J - 1, m_I + 1} \rangle + \frac{1}{2} \sqrt{(\frac{9}{2} + m_I)(\frac{9}{2} - m_I + 1)}\sqrt{(J - m_J)(J + m_J + 1)} \mid {J, \frac{9}{2}, m_J + 1, m_I - 1} \rangle$

$H_{HF}$ only couples states with the same $J, I, m_J + m_I = m_F$

$\langle J_1, m_{J_1}, m_{I_1}  \mid H_{HF} \mid J, m_{J}, m_{I} \rangle = (A + \frac{3}{2} Q \frac{1}{2IJ(2I-1)(2J-1)})(\frac{1}{2}  \sqrt{(\frac{9}{2} - m_I)(\frac{9}{2} + m_I + 1)}\sqrt{(J + m_J)(J - m_J + 1)} \delta_{J_1, J} \delta{m_{J_1}, m_{J} - 1} \delta{m_{I_1}, m_{I} + 1} + \frac{1}{2} \sqrt{(\frac{9}{2} + m_I)(\frac{9}{2} - m_I + 1)}\sqrt{(J - m_J)(J + m_J + 1)} \delta_{J_1, J} \delta{m_{J_1}, m_{J} + 1} \delta{m_{I_1}, m_{I} -1} + (A m_I m_J+  Q \frac{ \frac{3}{2}m_I m_J - IJ(I+1)(J+1)}{2IJ(2I-1)(2J-1)})\delta_{J_1, J} \delta{m_{J_1}, m_{J}} \delta{m_{I_1}, m_{I}} + 3 Q \frac{1}{2IJ(2I-1)(2J-1)}\vec{I} \cdot \vec{J} \vec{I} \cdot \vec{J}$


...

Too complicated

## 1. $m_F = -\frac{13}{2}$

The only possibility is $\mid ^{3} P _ 2, \frac{13}{2}, -\frac{13}{2}\rangle = \mid ^{3} P_ 2, -2, -\frac{9}{2}\rangle $

## 2. $m_F = -\frac{11}{2}$

The possibilities are

$\mid ^{3} P _ 2, \frac{13}{2}, -\frac{11}{2}\rangle = 0.83205029 \mid ^{3} P_ 2, -2, -\frac{7}{2}\rangle + 0.5547002  \mid ^{3} P_ 2, -1, -\frac{9}{2}\rangle $

$\mid ^{3} P _ 2, \frac{11}{2}, -\frac{11}{2}\rangle = -0.5547002 \mid ^{3} P_ 2, -2, -\frac{7}{2}\rangle + 0.83205029 \mid ^{3} P_ 2, -1, -\frac{9}{2}\rangle $

$\mid ^{3} P _ 1, \frac{11}{2}, -\frac{11}{2}\rangle = \mid ^{3} P_ 1, -1, -\frac{9}{2}\rangle $

$\mid ^{1} P _ 1, \frac{11}{2}, -\frac{11}{2}\rangle = \mid ^{3} P_ 1, -1, -\frac{9}{2}\rangle $

In [9]:
# Sort the same m_F states and put them into a matrix

def Subspace(mf):
    result = []
    for n, c in enumerate(Eigenvalues):
        for m in range(len(c)):
            if c[m][0][6] == mf:
                result.append((n, m))
    return result

In [44]:
for i, n in enumerate(Subspace(-11/2)):
    print len(CGcoefficients[n[0]][n[1]])
    print Eigenvalues[n[0]][n[1]]
print Subspace(9/2)

3
[('3P1', 1.0, 4.5, -1.0, -4.5, 5.5, -5.5)
 ('3P1', 1.0, 4.5, 0.0, -5.5, 5.5, -5.5)
 ('3P1', 1.0, 4.5, 1.0, -6.5, 5.5, -5.5)]
5
[('3P2', 2.0, 4.5, -2.0, -3.5, 6.5, -5.5)
 ('3P2', 2.0, 4.5, -1.0, -4.5, 6.5, -5.5)
 ('3P2', 2.0, 4.5, 0.0, -5.5, 6.5, -5.5)
 ('3P2', 2.0, 4.5, 1.0, -6.5, 6.5, -5.5)
 ('3P2', 2.0, 4.5, 2.0, -7.5, 6.5, -5.5)]
5
[('3P2', 2.0, 4.5, -2.0, -3.5, 5.5, -5.5)
 ('3P2', 2.0, 4.5, -1.0, -4.5, 5.5, -5.5)
 ('3P2', 2.0, 4.5, 0.0, -5.5, 5.5, -5.5)
 ('3P2', 2.0, 4.5, 1.0, -6.5, 5.5, -5.5)
 ('3P2', 2.0, 4.5, 2.0, -7.5, 5.5, -5.5)]
3
[('1P1', 1.0, 4.5, -1.0, -4.5, 5.5, -5.5)
 ('1P1', 1.0, 4.5, 0.0, -5.5, 5.5, -5.5)
 ('1P1', 1.0, 4.5, 1.0, -6.5, 5.5, -5.5)]
[(0, 10), (1, 9), (3, 11), (4, 10), (5, 9), (8, 10), (9, 9), (11, 9)]


In [ ]:
# I dot J Hamiltonian, returns a matrix that has the same dimension as CG and Eigen matrices, operates on the CG vector
# * * * * *    m_J = -2
# * * * * *    m_J = -1
# * * * * *    m_J = 0
# * * * * *    m_J = 1
# * * * * *    m_J = 2

def IJ(n, m):
    l = len(CGcoefficients[n][m])
    result = zeros((l, l))
    for i in range(l):
        if (CGcoefficients[n][m][i] != 0):
            for j in range(l):
                #if CGcoefficients[n][m]
                if (i == (j + 1)):            # I_+ J_- term
                    result[i][j] = 0.5 * sqrt(Eigenvalues[n][m][i][2] * (Eigenvalues[n][m][i][2] + 1) - Eigenvalues[n][m][i][4] * (Eigenvalues[n][m][i][4] + 1)) * sqrt(Eigenvalues[n][m][i][1] * (Eigenvalues[n][m][i][1] + 1) - Eigenvalues[n][m][i][3] * (Eigenvalues[n][m][i][3] - 1))
                if (i == (j - 1)):            # I_- J_+ term     
                    result[i][j] = 0.5 * sqrt(Eigenvalues[n][m][i][2] * (Eigenvalues[n][m][i][2] + 1) - Eigenvalues[n][m][i][4] * (Eigenvalues[n][m][i][4] - 1)) * sqrt(Eigenvalues[n][m][i][1] * (Eigenvalues[n][m][i][1] + 1) - Eigenvalues[n][m][i][3] * (Eigenvalues[n][m][i][3] + 1))
                if (i == j):                  # I_z J_z term
                    result[i][j] = Eigenvalues[n][m][i][3] * Eigenvalues[n][m][i][4]
    return result

In [49]:
print dot(IJ(0,0), IJ(0,0))

[[ 20.25   0.     0.  ]
 [  0.     0.     0.  ]
 [  0.     0.     0.  ]]


In [50]:
# Hyperfine interaction Hamiltonian, returns a matrix similar to IJ
# Energy in units of MHz
from numpy import dot

def HF(n, m):
    A = 0
    Q = 0
    if (Eigenvalues[n][m][0][0] == '3P1'):
        A = A_3P1
        Q = Q_3P1
    if (Eigenvalues[n][m][0][0] == '3P2'):
        A = A_3P2
        Q = Q_3P2
    if (Eigenvalues[n][m][0][0] == '1P1'):
        A = A_1P1
        Q = Q_1P1
    temp = IJ(n, m)
    I = Eigenvalues[n][m][0][2]
    J = Eigenvalues[n][m][0][1]
    result = A * temp + Q * (3 * dot(temp, temp) + 1.5 * temp - I * J * (I + 1) * (J + 1))/(2 * I * J * (2 * I - 1) * (2 * J - 1))
    return result

def matrix_element_HF(n1, m1, n2, m2):
    result = 0
    if (n1 == n2):
        result = dot(CGcoefficients[n1][m1], dot(HF(n2, m2), CGcoefficients[n2][m2]))
    return result

In [51]:
print matrix_element_HF(2, 3, 0, 0)

0


In [52]:
# HF Hamiltonian in m_F = f subspace

def HF_subspace(f):
    l = len(Subspace(f))
    result = zeros((l, l))
    for i, n in enumerate(Subspace(f)):
        for j, m in enumerate(Subspace(f)):
            result[i][j] = matrix_element_HF(n[0], n[1], m[0], m[1])
    return result

In [53]:
print HF_subspace(11/2)
print Subspace(11 /2 )

[[-1178.75           0.             0.             0.        ]
 [    0.         -1912.50961538     0.             0.        ]
 [    0.             0.          -528.28205128     0.        ]
 [    0.             0.             0.            -5.55      ]]
[(0, 11), (3, 12), (4, 11), (8, 11)]


In [54]:
from pandas import DataFrame
print DataFrame(HF_subspace(11/2))

         0            1           2     3
0 -1178.75     0.000000    0.000000  0.00
1     0.00 -1912.509615    0.000000  0.00
2     0.00     0.000000 -528.282051  0.00
3     0.00     0.000000    0.000000 -5.55

[4 rows x 4 columns]


In [56]:
from numpy import linalg as LA

w, v = LA.eig(HF_subspace(9/2))
print Subspace(9/2)
for i, n in enumerate(Subspace(9/2)):
    print len(CGcoefficients[n[0]][n[1]])
    print Eigenvalues[n[0]][n[1]]
print w
print v

[(0, 10), (1, 9), (3, 11), (4, 10), (5, 9), (8, 10), (9, 9), (11, 9)]
3
[('3P1', 1.0, 4.5, -1.0, 5.5, 5.5, 4.5)
 ('3P1', 1.0, 4.5, 0.0, 4.5, 5.5, 4.5)
 ('3P1', 1.0, 4.5, 1.0, 3.5, 5.5, 4.5)]
3
[('3P1', 1.0, 4.5, -1.0, 5.5, 4.5, 4.5)
 ('3P1', 1.0, 4.5, 0.0, 4.5, 4.5, 4.5)
 ('3P1', 1.0, 4.5, 1.0, 3.5, 4.5, 4.5)]
5
[('3P2', 2.0, 4.5, -2.0, 6.5, 6.5, 4.5)
 ('3P2', 2.0, 4.5, -1.0, 5.5, 6.5, 4.5)
 ('3P2', 2.0, 4.5, 0.0, 4.5, 6.5, 4.5)
 ('3P2', 2.0, 4.5, 1.0, 3.5, 6.5, 4.5)
 ('3P2', 2.0, 4.5, 2.0, 2.5, 6.5, 4.5)]
5
[('3P2', 2.0, 4.5, -2.0, 6.5, 5.5, 4.5)
 ('3P2', 2.0, 4.5, -1.0, 5.5, 5.5, 4.5)
 ('3P2', 2.0, 4.5, 0.0, 4.5, 5.5, 4.5)
 ('3P2', 2.0, 4.5, 1.0, 3.5, 5.5, 4.5)
 ('3P2', 2.0, 4.5, 2.0, 2.5, 5.5, 4.5)]
5
[('3P2', 2.0, 4.5, -2.0, 6.5, 4.5, 4.5)
 ('3P2', 2.0, 4.5, -1.0, 5.5, 4.5, 4.5)
 ('3P2', 2.0, 4.5, 0.0, 4.5, 4.5, 4.5)
 ('3P2', 2.0, 4.5, 1.0, 3.5, 4.5, 4.5)
 ('3P2', 2.0, 4.5, 2.0, 2.5, 4.5, 4.5)]
3
[('1P1', 1.0, 4.5, -1.0, 5.5, 5.5, 4.5)
 ('1P1', 1.0, 4.5, 0.0, 4.5, 5.5, 4.5)
 ('1P1'

In [57]:
w, v = LA.eig(HF_subspace(-9/2))
print Subspace(-9/2)
print w
print v

[(0, 1), (1, 0), (3, 2), (4, 1), (5, 0), (8, 1), (9, 0), (11, 0)]
[ -1.16018845e+03   2.64771780e+02  -1.92986802e+03  -5.29555886e+02
   6.35090572e+02  -2.62328733e+01  -1.91712665e+00  -0.00000000e+00]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


In [59]:
for i in range(-13, 15, 2):
    print Subspace(i / 2)
    print LA.eig(HF_subspace(i/2))[0]

[(3, 0)]
[-1891.25]
[(0, 0), (3, 1), (4, 0), (8, 0)]
[-1178.75       -1912.50961538  -528.28205128    -5.55      ]
[(0, 1), (1, 0), (3, 2), (4, 1), (5, 0), (8, 1), (9, 0), (11, 0)]
[ -1.16018845e+03   2.64771780e+02  -1.92986802e+03  -5.29555886e+02
   6.35090572e+02  -2.62328733e+01  -1.91712665e+00  -0.00000000e+00]
[(0, 2), (1, 1), (2, 0), (3, 3), (4, 2), (5, 1), (6, 0), (8, 2), (9, 1), (10, 0), (11, 1)]
[-1147.51382579   266.85441218  1399.20108027 -1943.19763209  -529.61420192
   627.98560323  1611.88873077   -40.35602269    -4.23777358    53.01879627
    -0.        ]
[(0, 3), (1, 2), (2, 1), (3, 4), (4, 3), (5, 2), (6, 1), (7, 0), (8, 3), (9, 2), (10, 1), (11, 2)]
[ -1.14062328e+03   2.63509704e+02   1.39565524e+03  -1.95283168e+03
  -5.28735792e+02   6.21452872e+02   1.60932921e+03   2.38055623e+03
  -4.80340607e+01  -5.10812856e-01   5.69698735e+01  -0.00000000e+00]
[(0, 4), (1, 3), (2, 2), (3, 5), (4, 4), (5, 3), (6, 2), (7, 1), (8, 4), (9, 3), (10, 2), (11, 3)]
[-1136.3692307